# Generated by Django 5.0.1 on 2024-04-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLicenta', '0003_bug_bugcontent_project_test_testcontent_user2bug_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
