# Generated by Django 5.0.1 on 2024-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLicenta', '0004_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_1', models.BooleanField()),
                ('detected_2', models.BooleanField()),
                ('detected_3', models.BooleanField()),
                ('located_1', models.BooleanField()),
                ('located_2', models.BooleanField()),
                ('located_3', models.BooleanField()),
                ('located_4', models.BooleanField()),
                ('fixed_1', models.BooleanField()),
                ('fixed_2', models.BooleanField()),
                ('fixed_3', models.BooleanField()),
                ('closed_1', models.BooleanField()),
                ('closed_2', models.BooleanField()),
            ],
            options={
                'db_table': 'bug_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defined_1', models.BooleanField()),
                ('defined_2', models.BooleanField()),
                ('defined_3', models.BooleanField()),
                ('defined_4', models.BooleanField()),
                ('specified_1', models.BooleanField()),
                ('specified_2', models.BooleanField()),
                ('specified_3', models.BooleanField()),
                ('specified_4', models.BooleanField()),
                ('specified_5', models.BooleanField()),
                ('specified_6', models.BooleanField()),
                ('executed_1', models.BooleanField()),
                ('executed_2', models.BooleanField()),
                ('evaluated_1', models.BooleanField()),
                ('evaluated_2', models.BooleanField()),
                ('evaluated_3', models.BooleanField()),
            ],
            options={
                'db_table': 'test_status',
                'managed': False,
            },
        ),
    ]
